### ISSUE TITLE
Fix for `requriments.txt` and please add LICENSE.

### ISSUE THREAD

**Issue by ajh123** [StanislavPetrovV/Minecraft#1]
# Introduction
The current `requriments.txt` is invalid. The normal `opensimplex` module does not work with Numba. Installing `opensimplex[numpy]` would fix all problems. Also having the dependencies without their version would have a possibility of incompatible modules being installed and thus the error ...
```
$ python main.py
pygame 2.1.2 (SDL 2.0.18, Python 3.10.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
```

## requriments.txt fix
```
pygame==2.5.0
moderngl==5.8.2
numba==0.57.1
PyGLM==2.7.0
numpy<1.25,>=1.21
opensimplex[numpy]==0.4.4
```

## LICENSE please

Also I recommend adding a LICENSE file, this tell people what they cant and can do with your code. Currently they are legally not allowed to do anything, so following your video and copying the code would be breaking the law (even if you want them to do so). https://choosealicense.com/ can help you to choose a LICENSE that you want. It is best practice to put a file called LICENSE inside the repository root. Then GitHub will parse the file and label the repository appropriately.

**Comment by OrangoMango** [comment]
I had to upgrade pygame in order make it work, but I still get this error: `Could not create GL context: GLXBadFBConfig pygame`. Do I need to upgrade something else?

**Comment by ajh123** [comment]
I'm not sure what you need but you do need a GPU (separate or integrated) that supports OpenGL 3.3 core profile. Most GPUs should support OpenGL 3.3 core profile. Pygame 2.5.0 works for me.

**Comment by OrangoMango** [comment]
Ah alright, I'm trying to run this on my raspberrypi,but I have OpenGL 2 instead of 3.
I understand, thanks

**Comment by Pludam** [comment]
Are there any other Python libs for OpenGL 2 that i could use for the raspberry pi?

**Comment by ajh123** [comment]
@Pludam You can use the same libraries but you need to change [this](https://github.com/StanislavPetrovV/Minecraft/blob/744da43f04127cefa6256c435e77420d39afe4a6/settings.py#L7) so it's something like `MAJOR_VER, MINOR_VER = 2, 0`. Also you may need to remake the shaders. I'm not an expert on Open GL 2 shaders.

**Comment by Pludam** [comment]
@ajh123 Right , didnt think of that .Anyways thanks for the Inge in the right direction

**Comment by StanislavPetrovV** [comment]
Added MIT license and updated requirements.txt

**Comment by theoparis** [comment]
I am currently getting this warning when installing opensimplex with numba here 🤔 
```
WARNING: opensimplex 0.4.4 does not provide the extra 'numpy'
```
